### PR TITLE
Add Mailfence

### PR DESCRIPTION
**Pull request by Mailfence-team**

### CODE REVIEW

**Comment by daviddavo** [comment]
I'm sorry, but this is "Just get my data", not "Just Delte Me".

We want to explain how to obtain your personal data, not delete it

**Comment by daviddavo** [comment]
This issue will be closed and marked as SPAM in one week If we don't receive a reply

**Comment by Mailfence-team** [comment]
> I'm sorry, but this is "Just get my data", not "Just Delte Me".

Apologies for the confusion.

> We want to explain how to obtain your personal data, not delete it

Corrected.

**Comment by daviddavo** [comment]
Thank you for your contribution

**Pull request merged**
